version: '3.8'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - zabbix_data:/var/lib/zabbix
      - ./scripts:/usr/local/bin
    depends_on:
      - zabbix-mysql
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
      - PHP_TZ=Europe/Moscow
    depends_on:
      - zabbix-mysql
      - zabbix-server
    networks:
      - zabbix-net

  zabbix-mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-net

  zabbix-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: zabbix/zabbix-agent:ubuntu-6.0-latest
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
    volumes:
      - ./scripts:/usr/local/bin
      - ./zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf:ro
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

volumes:
  zabbix_data:
  mysql_data:

networks:
  zabbix-net:
    driver: bridge
